name: assimalign.componentmodel.mapping.build.ci

on:
  push:
    paths: 
    - 'src/Assimalign.ComponentModel.Mapping/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    
    - name: Restore Project
      run: dotnet restore 
      working-directory: './src/Assimalign.ComponentModel.Mapping'
    
    - name: Build Project
      run: dotnet build --configuration Release --no-restore
      working-directory: './src/Assimalign.ComponentModel.Mapping'

    - name: Run Unit Tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: './tests/Assimalign.ComponentModel.MappingTests'